require("plugins")
require("utils")
require("lualine-setup")
require("mason-setup")
require("treesitter-setup")
require("cmp-setup")
require("snippet-setup")
require("dap-setup")
require("comments-setup")
require("telescope-setup")
require("null-ls-setup")
require("indent-blanklin-setup")
require("fire-nvim-setup")
require("align-setup")

