local on_attach = require("lsp.attached")
return {
	on_attach = on_attach,
	filetypes = { "php", "blade" },
	settings = {
		intelephense = {
			stubs = { "bcmath",
				"/Users/joshkennedy/dotfiles/.config/php-stubs",
				"bz2",
				"calendar",
				"Core",
				"curl",
				"date",
				"dba",
				"dom",
				"enchant",
				"fileinfo",
				"filter",
				"ftp",
				"gd",
				"gettext",
				"hash",
				"iconv",
				"imap",
				"intl",
				"json",
				"ldap",
				"libxml",
				"mbstring",
				"mcrypt",
				"mysql",
				"mysqli",
				"password",
				"pcntl",
				"pcre",
				"PDO",
				"pdo_mysql",
				"Phar",
				"readline",
				"recode",
				"Reflection",
				"regex",
				"session",
				"SimpleXML",
				"soap",
				"sockets",
				"sodium",
				"SPL",
				"standard",
				"superglobals",
				"sysvsem",
				"sysvshm",
				"tokenizer",
				"xml",
				"xdebug",
				"xmlreader",
				"xmlwriter",
				"yaml",
				"zip",
				"zlib",
				"wordpress", --using custom stubs more up to date
				"woocommerce",
				"acf-pro",
				"acf-stubs",
				"wordpress-globals", -- using custom stubs more up to date
				"wp-cli",
				"genesis",
				"polylang",
				"sbi" },
			format = {
				enable = true,
				braces = "k&r",
			},
			diagnostics = { enable = true },
			files = {
				maxSize = 10000000,
			},
		},
	}
}
