local Color, colors, Group, groups, styles = require('colorbuddy').setup()

Color.new("pink", "#C17DCD")
Color.new("darkPurp", "#8D78BE")
Color.new("Purp", "#BB9AF7")
Color.new("whitePurp","#ddbcf9")
Color.new("white", "#ffffff")
Color.new("darkBG","#202336")
Color.new("Green", "#2AC3DE")
Color.new("Orange", "#F79A62")
-- Group.new('@variable', colors.pink, nil, styles.bold)
-- Group.new('@_tag', colors.pink, nil, styles.bold)
-- Group.new('@attribute', colors.pink, nil, styles.bold)
-- Group.new('@type.qualifier', colors.darkPurp, nil, nil)
-- Group.new('@keyword.return', colors.Purp, nil, nil)
-- -- Group.new("@variable.builtin", colors.Green, nil, styles.bold)
-- Group.new("@silly", colors.darkBG ,colors.Green,nil)
-- Group.new("@magic_method", colors.darkBG, colors.pink,nil)
-- Group.new("@constructor.create", colors.Green, nil,nil)
-- Group.new("@punctuation.bracket.index", colors.Orange,nil,nil)
-- Group.new("todo", colors.Orange,colors.white ,nil)
-- Group.new("todo", colors.white,colors.Orange ,nil)
Group.new("todo",nil,colors.whitePurp)
Group.new("@customTodo",colors.Orange,colors.whitePurp)
Group.new("@text.todo",colors.white,colors.Purp)
